name: Run Python Function

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python Function
      run: |
        python3 -c "
        import os

        from tests.CheckGraphics import check_graphics

        base_folder = 'Base'
        folders = os.listdir(base_folder)
        for folder in folders:
            result, msg = check_graphics(os.path.join(base_folder, folder))
            if not result :
                print('Check thành công')
            else:
                print('nonononono')
        "
